* Arch Setup
** Pacman
   - Update System: 
     #+BEGIN_SRC shell
     sudo pacman -Syu
     #+END_SRC
   - Removing unused packages (orphans)
     For recursively removing orphans and their configuration files:
     #+BEGIN_SRC shell
     pacman -Rns $(pacman -Qtdq)
     #+END_SRC
   - Fix database error: could not open file /var/lib/pacman/sync/antergos.db: Unrecognized archive format...
     #+BEGIN_SRC shell
     sudo pacman -Syy
     #+END_SRC
     Notes: Passing two --refresh or -y flags will force a refresh of all package databases, even if they appear to be up-to-date.

** System backup
   1. Generate package list
      #+BEGIN_SRC shell
      pacman -Qqe > ~/Dotfiles/ArchPackageList.txt
      #+END_SRC
   2. Reinstall the packages
      #+BEGIN_SRC shell
      sudo pacman -S `cat ~/Dotfiles/ArchPackageList.txt`
      #This will also work, but Pacman will exit if you have a package
      #installed that is not in the repositories.
      #+END_SRC
   3. *Grsync*
      My backup path:
      /home
      /run/media/ztlevi/65e80ac4-1f5a-4028-bfa2-885178ebdfa4
      #+BEGIN_SRC shell
      # Grsync additional options
      --exclude-from="/home/ztlevi/Dotfiles/grsync-rules"
      #+END_SRC
** Nvidia Drivers
   And we have the nvidia-installer doing all this automatic:
   #+BEGIN_SRC shell
   sudo pacman -S nvidia-installer
   # To test the installation (-t)
   nvidia-installer -b -t
   # real installation:
   sudo nvidia-installer -b
   #+END_SRC

** Chinese Encoding and font issue
   1. Install *noto-fonts-cjk* (Google Noto CJK fonts), which supports Chinese, Japanese, Korean.
   2. Edit */etc/fonts/conf.d/65-nonlatin.conf*, put the preferred font e.g. Noto Sans CJK SC in the file under *sans-serif* family tag.
      #+BEGIN_SRC 
      <!-- chinese fonts are actually serifed -->
      <family>Noto Sans CJK SC</family> <!-- han (zh-cn,zh-tw) -->
      #+END_SRC

** Developer tools
   - JDK
   - Node, NPM
   - Xampp: Apache, PHP, Phpmyadmin tool
   - Eclipse jee
   - Netbeans
   - Intellij idea
   - vim-gnome: Install vim-gnome instead of just vim, because it including more features like xterm-clipboard.
   - zeal: Developer docsets.

** Other tools
   - *Grub-customizer* :boot menu setting
   - *Latte Dock* :Dock just like Mac Dock
     #+BEGIN_SRC shell
     sudo pacman -Syu
     # install dependencies
     sudo pacman -S cmake extra-cmake-modules python plasma-framework plasma-desktop
     sudo pacman -S latte-dock
     #+END_SRC

   - Dropbox: Sync files
   - Grsync: backup tool
   - Typora: Markdown editor
   - Pandoc: Conversion between markup formats
   - Xflux-gui(Not working right now): GUI flux, like night shift
   - Redshift: night shift
   - OBS: video recorder
   - Webtorrent: torrent downloader
     Netease: Music client
   - Slack
   - Telegram
   - Electronic Wechat: Wechat built on Electron
   - Sogou pinyin: Chinese input
     1. Install fcitx-sogoupinyin
     2. Install fcitx-gtk2, fix Chrome cannot use fcitx
     3. Put the following codes in the ~/.xprofile
        #+BEGIN_SRC shell
        export GTK_IM_MODULE=fcitx
        export QT_IM_MODULE=fcitx
        export XMODIFIERS="@im=fcitx"
        #+END_SRC
     4. You may need to install kcm-fcitx for KDE.

   - Youdao-dict: Chinese <-> English Dictionary

** Reduce startup and shutdown timeout

   1. /etc/systemd/system.conf:
      #+BEGIN_SRC 
      DefaultTimeoutStartSec=10s
      DefaultTimeoutStopSec=10s
      #+END_SRC

   2. Then reload systemd by
      #+BEGIN_SRC language
      systemctl daemon-reload
      #+END_SRC

** Fix Dual Boot time conflicts
   Linux: The hardware clock can be queried and set with the timedatectl command. To change the hardware clock time standard to localtime, use: ~timedatectl set-local-rtc 1~

   OR

   Windows: To fix it, just hit Start and type regedit.exe in the search box. Hit Enter and navigate to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation. Right click anywhere in the right pane and hit New > DWORD (32-bit) Value. Name it RealTimeIsUniversal, then double click on it and give it a value of 1.
** Key Bindings
   - Change Application Hide(Minimize window) to Ctrl-h
   - Change Application Quit(Close Window) to Ctrl-q
