* Ting Zhou's Configuration for space-vim, ZSH, Dotfiles and Atom
  
** Installation

   The root directory should be *~/Dotfiles/*
   
   Use
   #+BEGIN_SRC shell
   git clone https://github.com/ztlevi/Dotfiles.git ~/Dotfiles
   #+END_SRC

*** space-vim

    1. Install *git, vim, curl* first.
       ~vim --version~ to check your vim has +clipboard and +python/python3 support
       - For Mac: ~brew install macvim --with-override-system-vim~
       - For Linux, install *vim-clipboard* instead of vim

    2. Install space-vim:
       #+BEGIN_SRC shell
       cd ~/Dotfiles
       ./installspace-vim.sh
       #+END_SRC
    3. Update the plugin with =:PlugUpdate=

*** ZSH

    1. Install zsh first, instructions [[https://github.com/robbyrussell/oh-my-zsh/wiki/Installing-ZSH][here]].
       #+BEGIN_SRC shell
       # set zsh as default
       chsh -s $(which zsh)
       #+END_SRC

    2. Install oh-my-zsh:
       #+BEGIN_SRC shell
       sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
       #+END_SRC
      
    3. Install Tumx

       Furthermore, to install Tmux Package Manager: 
       #+BEGIN_SRC shell
       git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
       #+END_SRC

       Notes: *tmux-yank* package requirements [[https://github.com/tmux-plugins/tmux-yank][here]]. 
       Mac: ~brew install reattach-to-user-namespace~
       Linux: ~pacman -S xsel~

    4. The instructions is in OhMyZSH.org

*** Dotfiles
    1. Some dependencies here, and you will need to install python.
       #+BEGIN_SRC shell
       npm i -g js-beautify npm
       #+END_SRC
    2. Put the dotfiles in the home directory:
       #+BEGIN_SRC shell
       cd ~/Dotfiles
       ./install.sh
       #+END_SRC

*** Atom
    Sync with sync-settings packge.

    1. Create personal access token on github
    2. Copy the GistID: 4bda37259f0d4e181442afff706c0cb2

*** VSCode
    Sync GistID: a21a200d929d90a2267b820f3e9f0e4a
    
** Mac Keybindings

   Settings are described in /Mac\_keybindings/ReadMe.md/
   
** Fonts

   1. Roboto Mono for Powerline
   2. Ubuntu Mono and the one for Powerline
   3. Source Code Pro for Powerline

** Notes

   1. Xmodmap file is used for key tweak on linux.
   2. Fix npm permission.
      #+BEGIN_SRC shell
      sudo chown -R $(whoami) /usr/local 
      #+END_SRC
