* Ting Zhou's Configuration for space-vim, ZSH, Dotfiles and Atom

** Installation

   The root directory should be *~/Dotfiles/*

   Use
   #+BEGIN_SRC shell
     git clone https://github.com/ztlevi/Dotfiles.git ~/Dotfiles
   #+END_SRC

*** space-vim

    1. Install *git, vim/neovim, curl* first.
       1. vim
          ~vim --version~ to check your vim has +clipboard and +python/python3 support
          - For Mac: ~brew install macvim --with-override-system-vim~
          - For Linux, install *gvim* instead of vim (with +clipboard support)
       2. neovim
          Python support script is already written in /installspace-vim.sh/. Make sure you have Python 2 or 3 installed.
          - For Mac: ~brew install neovim~

    2. Install space-vim:
       #+BEGIN_SRC shell
         cd ~/Dotfiles
         ./installspace-vim.sh
       #+END_SRC
    3. Update the plugin with =:PlugUpdate=

*** ZSH

    1. Install zsh first, instructions [[https://github.com/robbyrussell/oh-my-zsh/wiki/Installing-ZSH][here]].
       #+BEGIN_SRC shell
         # set zsh as default
         chsh -s $(which zsh)
       #+END_SRC

    2. Install oh-my-zsh:
       #+BEGIN_SRC shell
         sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
       #+END_SRC

    3. The instructions is in OhMyZSH.org

*** Tmux
    1. Install Tumx using system package manager like homebrew, apt-get, pacman.

       #+BEGIN_SRC shell
         brew install tmux
       #+END_SRC

    2. Furthermore, to install Tmux Package Manager:
       #+BEGIN_SRC shell
         git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
       #+END_SRC

       Notes: *tmux-yank* package requirements [[https://github.com/tmux-plugins/tmux-yank][here]].
       Mac: ~brew install reattach-to-user-namespace~
       Linux: ~pacman -S xsel~

    3. Key bindings
       - prefix: I set it to C-x

       - prefix + I: Installs new plugins from GitHub or any other git repository. Refreshes TMUX environment

       - prefix + U: updates plugin(s)

       - prefix + alt + u: remove/uninstall plugins not on the plugin list

*** fzf
    - Homebrew or Linuxbrew
      #+BEGIN_SRC shell
      brew install fzf

      # To install useful key bindings and fuzzy completion:
      $(brew --prefix)/opt/fzf/install
      #+END_SRC

*** NVM
    Use nvm as node version manager.
    #+BEGIN_SRC shell
      curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
      nvm install 6
      nvm use 6

      # set the system as default node
      nvm alias default system
    #+END_SRC

*** Other Dependencies
    1. System package manager dependencies:
       #+BEGIN_SRC shell
         brew install screenfetch trash asciinema
       #+END_SRC
    2. NPM dependencies here, and you will need to install python.
       #+BEGIN_SRC shell
         npm i -g npm js-beautify hexo-cli reveal-md phantomjs
       #+END_SRC
    3. Put the dotfiles in the home directory:
       #+BEGIN_SRC shell
         cd ~/Dotfiles
         ./install.sh
       #+END_SRC
    4. node and anaconda3
       #+BEGIN_SRC shell
         brew install node@8
         brew cask install anaconda
       #+END_SRC

** Mac Keybindings

   Settings are described in /Mac\_keybindings/ReadMe.md/

** Homebrew Backup
   - Backup
     #+BEGIN_SRC shell
       brew bundle dump --force --file="~/Library/Mobile Documents/com~apple~CloudDocs/PackageManagerLists/Brewfile"
     #+END_SRC
   - Restore
     #+BEGIN_SRC shell
       brew bundle --file="~/Library/Mobile Documents/com~apple~CloudDocs/PackageManagerLists/Brewfile"
     #+END_SRC
   - Clean up
     #+BEGIN_SRC shell
       brew bundle cleanup --file="~/Library/Mobile Documents/com~apple~CloudDocs/PackageManagerLists/Brewfile"
     #+END_SRC

** Fonts

   1. Roboto Mono for Powerline
   2. Ubuntu Mono and the one for Powerline
   3. Source Code Pro for Powerline
   4. Operator Mono and Lig
   5. Monofur for Powerline
   6. Menlo - Regular

** Notes

   1. Xmodmap file is used for key tweak on linux.
   2. Fix npm permission.
      #+BEGIN_SRC shell
        sudo chown -R $(whoami) /usr/local
      #+END_SRC
