* Ting Zhou's Configuration for space-vim, Dotfiles and Atom
  
** Installation

   The root directory should be *~/Dotfiles/*
   
   Use
   #+BEGIN_SRC shell
   git clone https://github.com/ztlevi/Dotfiles.git ~/Dotfiles
   #+END_SRC

   or

   #+BEGIN_SRC shell
   git clone git@github.com:ztlevi/Dotfiles.git ~/Dotfiles
   #+END_SRC

*** space-vim

    1. Install *git, vim, curl* first.
       Notes: Vim +clipboard, fix no * and + register problem
       For Mac: ~brew install vim~, then vim locates under the */usr/local/bin/vim*
       For Ubuntu, install vim-gnome
       #+BEGIN_SRC shell
       sudo apt install vim-gnome
       #+END_SRC

    2. Install space-vim:
       #+BEGIN_SRC shell
        cd ~/Dotfiles
        ./installspace-vim.sh
       #+END_SRC
    3. Update the plugin with =:PlugUpdate=

*** Dotfiles

    Install zsh first, =brew install zsh zsh-completions= or =apt install zsh= on Ubuntu.

    Install oh-my-zsh:
    #+BEGIN_SRC shell
      sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    #+END_SRC
      
    Put the dotfiles in the home directory:
    #+BEGIN_SRC shell
      cd ~/Dotfiles
      ./install.sh
    #+END_SRC

*** Atom

    Sync with sync-settings packge.

    1. Create personal access token on github
    2. Copy the GistID

** Mac Keybindings

   Settings are described in /Mac\_keybindings/ReadMe.md/

** Fonts

   1. Roboto Mono for Powerline
   2. Ubuntu Mono and the one for Powerline
   3. Source Code Pro for Powerline

** Notes

   1. Xmodmap file is used for key tweak on linux.
   2. Fix npm completion permission.
      https://docs.npmjs.com/getting-started/fixing-npm-permissions .
