#+TITLE: UbuntuSetup

* Theme setup
- Gnome:
  - Install
    Gnome user theme extension https://extensions.gnome.org/extension/19/user-themes/.

    Get the Flat Remix theme, and icons. Then select them in Gnome-tweaks.
    #+BEGIN_SRC bash
sudo apt install chrome-gnome-shell
sudo add-apt-repository ppa:daniruiz/flat-remix
sudo apt-get update
sudo apt-get install flat-remix-gnome flat-remix-gtk flat-remix
    #+END_SRC

  - [[https://extensions.gnome.org/extension/307/dash-to-dock/][Dash to Dock]] is an alternative to the default dock.

* Libraries
Update apt with ~sudo apt-get update~

1. Apt:
   #+BEGIN_SRC shell
sudo apt-get install build-essential curl wget file git zsh p7zip-full ranger clang-format python3-pip net-tools exfat-fuse exfat-utils
   #+END_SRC

2. [[http://linuxbrew.sh/][Linuxbrew]]:
   #+BEGIN_SRC shell
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
brew install ripgrep cmake ninja tmux fzf neovim
   #+END_SRC

3. Nodejs (LTS): [[https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions][Tutorial]]
   #+BEGIN_SRC shell
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
   #+END_SRC

4. GCC7
   #+BEGIN_SRC shell
# Install the gcc-7 packages:

sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install g++-7 -y

# Set it up so the symbolic links gcc, g++ point to the newer version:

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 \
                         --slave /usr/bin/g++ g++ /usr/bin/g++-7
sudo update-alternatives --config gcc
gcc --version
g++ --version
   #+END_SRC

5. Java: [[http://tipsonubuntu.com/2016/07/31/install-oracle-java-8-9-ubuntu-16-04-linux-mint-18/][Tutorial]]
   #+BEGIN_SRC shell
sudo add-apt-repository ppa:webupd8team/java
sudo apt update; sudo apt install oracle-java8-installer
sudo apt install oracle-java8-set-default
   #+END_SRC

6. Other applications
   #+BEGIN_SRC shell
# Screenshot
sudo apt-get install shutter
   #+END_SRC

7. Tilix: https://gnunn1.github.io/tilix-web/
   #+BEGIN_SRC shell
sudo add-apt-repository ppa:webupd8team/terminix
sudo apt-get update
sudo apt-get install tilix

# Fix tilix issue
ln -s /etc/profile.d/vte-2.91.sh /etc/profile.d/vte.sh
   #+END_SRC

* Ubuntu Applications
1. Gnome-terminal: Use login shell, Go to ~Edit~ -> ~Preferences~ -> ~Profiles~ -> ~Command~ ->
   Check ~Run command as a login shell~
2. GNOME Tweaks
3. Diodon: Clipboard

* Scheenshot & Record
** Take Screenshot
Quickly take a screenshot of the desktop, a window, or an area at any time using these global keyboard shortcuts:

- ~Prt Scrn~ to take a screenshot of the desktop.

- ~Alt+Prt Scrn~ to take a screenshot of a window.

- ~Shift+Prt Scrn~ to take a screenshot of an area you select.

When you use a keyboard shortcut, the image is automatically saved in your Pictures folder in your home folder with a file name that begins with Screenshot and includes the date and time it was taken.

You can also hold down ~Ctrl~ with any of the above shortcuts to copy the screenshot image to the clipboard instead of saving it.

** Record Screen
You can make a video recording of what is happening on your screen:

1. Press ~Ctrl+Alt+Shift+R~ to start recording what is on your screen.
   A red circle is displayed in the top right corner of the screen when the recording is in progress.

2. Once you have finished, press ~Ctrl+Alt+Shift+R~ again to stop the recording.

3. The video is automatically saved in your Videos folder in your home folder, with a file name that starts with Screencast and includes the date and time it was taken.
