#+TITLE: UbuntuSetup

* Theme setup
Get the [[https://www.opendesktop.org/p/1214931/][Flat Remix GTK theme]], and icons

* Libraries
Update apt with ~sudo apt-get update~

1. Install [[http://linuxbrew.sh/][Linuxbrew]]:
   #+BEGIN_SRC shell
sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"

sudo apt-get install build-essential curl file git
   #+END_SRC

2. Use Linuxbrew to install dependencies
   #+BEGIN_SRC shell
brew install git curl wget ripgrep python3 node@8 gcc@7 cmake ninja clang-format tmux
brew link gcc@7
   #+END_SRC

3. Nodejs (LTS): [[https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions][Tutorial]]
   #+BEGIN_SRC shell
wget -qO- https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
   #+END_SRC

4. Java: [[http://tipsonubuntu.com/2016/07/31/install-oracle-java-8-9-ubuntu-16-04-linux-mint-18/][Tutorial]]
   #+BEGIN_SRC shell
sudo add-apt-repository ppa:webupd8team/java
sudo apt update; sudo apt install oracle-java8-installer
sudo apt install oracle-java8-set-default
   #+END_SRC

* Ubuntu Applications
1. Gnome-terminal: Use login shell, Go to ~Edit~ -> ~Preferences~ -> ~Profiles~ -> ~Command~ ->
   Check ~Run command as a login shell~
2. GNOME Tweaks
3. Diodon: Clipboard

* Scheenshot & Record
** Take Screenshot
Quickly take a screenshot of the desktop, a window, or an area at any time using these global keyboard shortcuts:

- ~Prt Scrn~ to take a screenshot of the desktop.

- ~Alt+Prt Scrn~ to take a screenshot of a window.

- ~Shift+Prt Scrn~ to take a screenshot of an area you select.

When you use a keyboard shortcut, the image is automatically saved in your Pictures folder in your home folder with a file name that begins with Screenshot and includes the date and time it was taken.

You can also hold down ~Ctrl~ with any of the above shortcuts to copy the screenshot image to the clipboard instead of saving it.

** Record Screen
You can make a video recording of what is happening on your screen:

1. Press ~Ctrl+Alt+Shift+R~ to start recording what is on your screen.
   A red circle is displayed in the top right corner of the screen when the recording is in progress.

2. Once you have finished, press ~Ctrl+Alt+Shift+R~ again to stop the recording.

3. The video is automatically saved in your Videos folder in your home folder, with a file name that starts with Screencast and includes the date and time it was taken.
