#+TITLE: UbuntuSetup

* Theme setup
Get the [[https://www.opendesktop.org/p/1214931/][Flat Remix GTK theme]], and icons

* Libraries
Update apt with ~sudo apt-get update~
1. Presiqusites
   #+BEGIN_SRC shell
sudo apt install curl wget cmake
   #+END_SRC

2. Nodejs (LTS): [[https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions][Tutorial]]
   #+BEGIN_SRC shell
wget -qO- https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
   #+END_SRC
3. python
   #+BEGIN_SRC shell
sudo apt install python3-pip
   #+END_SRC
4. Git
   #+BEGIN_SRC shell
sudo apt-get purge runit
sudo apt-get purge git-all
sudo apt-get purge git
sudo apt-get autoremove
sudo apt update
sudo apt install git
   #+END_SRC
5. Ripgrep
   If you're a **Debian** user (or a user of a Debian derivative like **Ubuntu**),
   then ripgrep can be installed using a binary `.deb` file provided in each
   [[https://github.com/BurntSushi/ripgrep/releases][ripgrep release]].

   #+BEGIN_SRC shell
curl -LO https://github.com/BurntSushi/ripgrep/releases/download/0.10.0/ripgrep_0.10.0_amd64.deb
sudo dpkg -i ripgrep_0.10.0_amd64.deb
   #+END_SRC
6. GCC
   Install the gcc-7 packages:
   #+BEGIN_SRC shell
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install g++-7 -y
   #+END_SRC

   Set it up so the symbolic links gcc, g++ point to the newer version:
   #+BEGIN_SRC shell
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 \
    --slave /usr/bin/g++ g++ /usr/bin/g++-7
sudo update-alternatives --config gcc
gcc --version
g++ --version
   #+END_SRC

* Ubuntu Applications
1. GNOME Tweaks
2. Diodon: Clipboard

* Scheenshot & Record
** Take Screenshot
Quickly take a screenshot of the desktop, a window, or an area at any time using these global keyboard shortcuts:

- ~Prt Scrn~ to take a screenshot of the desktop.

- ~Alt+Prt Scrn~ to take a screenshot of a window.

- ~Shift+Prt Scrn~ to take a screenshot of an area you select.

When you use a keyboard shortcut, the image is automatically saved in your Pictures folder in your home folder with a file name that begins with Screenshot and includes the date and time it was taken.

You can also hold down ~Ctrl~ with any of the above shortcuts to copy the screenshot image to the clipboard instead of saving it.

** Record Screen
You can make a video recording of what is happening on your screen:

1. Press ~Ctrl+Alt+Shift+R~ to start recording what is on your screen.
   A red circle is displayed in the top right corner of the screen when the recording is in progress.

2. Once you have finished, press ~Ctrl+Alt+Shift+R~ again to stop the recording.

3. The video is automatically saved in your Videos folder in your home folder, with a file name that starts with Screencast and includes the date and time it was taken.
